soroban contract invoke^
  --id CCJFMEIHPQDCBO3B77NSCFEE32CXBEA6ZWPTTOCQQ6ONHQDFHSSANQ2U^
  --source SDNTGAOPMR2VKBJUKYHWJOCCNBJA4EAXG5FTGFGHZPGPWLZM7TF63O5J^
  --rpc-url https://rpc-futurenet.stellar.org:443/^
  --network-passphrase "Test SDF Future Network ; October 2022"^
  -- initialize^
  --admin GBTJNUMDSUWBYAFSNWZQFTLORJH7YM6VYADSEPUCD6IU7G4IQGM7EQYN^
  --liquidator GB2LLVHSVBK7OBV5FRBR4PTUHTOVY2ROE2HLFGD6K3FSBN6EVXFOJBPQ