name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - name: Build
        run: cd contracts/vault_contract && cargo build --target wasm32-unknown-unknown --release && cd .. && cargo build --verbose
      - name: Run tests
        run: cd contracts && cargo test --verbose